##########################################################
# Aider Configuration
##########################################################

#############
# Main model:
#model: openrouter  # Best balance of capability and cost

#################
# Model settings:
max-chat-history-tokens: 8000  # Reasonable limit to prevent excessive token usage
map-tokens: 2000  # Good default for repo mapping
map-refresh: auto  # Automatically refresh repo map when needed

################
# History Files:
restore-chat-history: true  # Maintain context between sessions
llm-history-file: .aider.llm.history  # Log LLM conversations for review

##################
# Output settings:
pretty: true  # Colorized output
stream: true  # Stream responses for better UX
show-diffs: true  # Show diffs when committing changes
code-theme: monokai  # Popular code highlighting theme

###############
# Git settings:
auto-commits: false  # Manual control over commits
dirty-commits: false  # Don't automatically commit dirty files
attribute-author: true  # Attribute AI changes in git
attribute-committer: true  # Attribute AI as committer
attribute-commit-message-author: true  # Prefix commit messages with 'aider: '

########################
# Fixing and committing:
auto-lint: true  # Automatically lint after changes
auto-test: false  # Manual control over test runs

############
# Analytics:
analytics: false  # Disable analytics for privacy

############
# Upgrading:
check-update: true  # Check for updates on launch

#################
# Other settings:
vim: true  # Use standard editing mode (change to true if you prefer vim)
suggest-shell-commands: true  # Allow suggesting shell commands
fancy-input: true  # Enable fancy input with history and completion
multiline: false  # Enable multi-line input mode
notifications: true  # Enable notifications when responses are ready
detect-urls: true  # Detect and offer to add URLs to chat
