##########################################################
# Aider Configuration
##########################################################
---
#############
# Main model:
# Best balance of capability and cost
model: deepinfra/openai/gpt-oss-120b
# model: deepseek/deepseek-chat
# model: gemini/gemini-2.0-flash
#################
# Model settings:
# Reasonable limit to prevent excessive token usage
max-chat-history-tokens: 8000
# Good default for repo mapping
map-tokens: 2000
# Automatically refresh repo map when needed
map-refresh: auto
################
# History Files:
# Maintain context between sessions
restore-chat-history: true
# Log LLM conversations for review
llm-history-file: .aider.llm.history
##################
# Output settings:
# Colorized output
pretty: true
# Stream responses for better UX
stream: true
# Show diffs when committing changes
show-diffs: true
# Popular code highlighting theme
code-theme: monokai
###############
# Git settings:
# Manual control over commits
auto-commits: true
# Don't automatically commit dirty files
dirty-commits: false
# Attribute AI changes in git
attribute-author: true
# Attribute AI as committer
attribute-committer: true
# Prefix commit messages with 'aider: '
attribute-commit-message-author: true
########################
# Fixing and committing:
# Automatically lint after changes
auto-lint: true
# Manual control over test runs
auto-test: false
############
# Analytics:
# Disable analytics for privacy
analytics: false
############
# Upgrading:
# Check for updates on launch
check-update: true
#################
# Other settings:
# Use standard editing mode (change to true if you prefer vim)
vim: true
# Allow suggesting shell commands
suggest-shell-commands: true
# Enable fancy input with history and completion
fancy-input: true
# Enable multi-line input mode
multiline: true
# Enable notifications when responses are ready
notifications: true
# Detect and offer to add URLs to chat
detect-urls: true
# Dark mode
dark-mode: true
