#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2023 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================
# All SpaceVim options are below [options] snippet
[options]
    automatic_update = true
    default_indent = 2
    expand_tab = true
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors, the type of the value is boolean, true or false.
    enable_guicolors = true
    # options for statusline
    # Set the statusline separators of statusline, default is "arrow"
    statusline_separator = "arrow"
    # Set the statusline separators of inactive statusline
    statusline_iseparator = "bar"
    buffer_index_type = 4
    # Display file type icon on the tabline, If you do not have nerd fonts
    # installed, please change the value to false
    enable_tabline_filetype_icon = true
    # Display current mode text on statusline, by default It is disabled,
    # only color will be changed when switch modes.
    # checkers options
    enable_statusline_mode = true
    # left sections of statusline
    statusline_left_sections = [
      'winnr',
      'major mode',
      'filename',
      'fileformat',
      'minor mode lighters',
      'version control info',
      'search status'
    ]
    # right sections of statusline
    statusline_right_sections = [
      'cursorpos',
      'percentage',
      'input method',
      'date',
      'time'
    ]
    lint_engine = "ale"
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"
    vimcompatible = true

[[layers]]
name = "default"

# Enable autocomplete layer
[[layers]]
    name = "autocomplete"
    auto_completion_tab_key_behavior = "cycle"
    auto_completion_delay = 200
    auto_completion_complete_with_key_sequence = "nil"
    auto_completion_complete_with_key_sequence_delay = 0.1
    auto-completion-return-key-behavior = "complete"

[[layers]]
name = 'shell'
default_position = 'bottom'
default_height = 30

[[layers]]
    name = "core#banner"

[[layers]]
    name = "core#statusline"

[[layers]]
    name = "core#tabline"

[[layers]]
    name = "checkers"
    lint_on_the_fly = true
    lint_on_save = true
    lint_exclude_filetype	= []
    open_error_list = 2
    show_cursor_error = true

[[layers]]
    name = "format"
    format_method = "codefmt"
    format_on_save = true
    silent_format = true

[[layers]]
  name = 'edit'
  autosave_timeout = 2000
 # autosave_events = ['InsertLeave', 'TextChanged']
  autosave_events = []
  autosave_all_buffers = true

[[layers]]
    name = "ui"
    enable_sidebar = true
    enable_scrollbar = false
    enable_indentline = true
    enable_cursorword = false
    indentline_char = '|'
    conceallevel = 0
    concealcursor = ''
    cursorword_delay = 50
    cursorword_exclude_filetype = []
    indentline_exclude_filetype = []

[[layers]]
  name = "colorscheme"
  # set spacevim theme. by default colorscheme layer is not loaded,
  # if you want to use more colorscheme, please load the colorscheme
  # layer, the value of this option is a string.
  colorscheme = "gruvbox"
  colorscheme_bg = "dark"
  random_theme = false

[[layers]]
  name = "debug"
  debugger_plugin = "vimspector"

[[layers]]
  name = "foldsearch"
  foldsearch_highlight = true

[[layers]]
  name = "lang#cmake"

[[layers]]
  name = "lang#lua"

[[layers]]
  name = "lang#java"
  format_on_save = true
  java_formatter_jar = '~/javaformatter/google-java-format.jar'
  java_file_head = [
    '/**',
    ' * @author : `fnamemodify(expand("~"), ":t")`',
    ' * @created : `strftime("%Y-%m-%d")`',
    '**/',
    ''
  ]

[[layers]]
  name = "lang#markdown"
  listItemIndent = "1"
  enableWcwidth = true
  listItemChar = "*"
  enabled_formater = ["remark", "prettier"]

[[layers]]
  name = "lang#php"

[[layers]]
    name = "lang#html"

[[layers]]
    name = "lang#sh"
    bash_file_head = []

[[layers]]
    name = "lang#jsonnet"

[[layers]]
  name = 'lsp'
  enabled_clients = ['intelephense', 'pyright', 'rust_analyzer']

[[layers]]
    name = "lang#python"
    python_file_head = []
    enable_typeinfo = true
    format_on_save = true
    enabled_linters = ['python','pylint']
    enabled_clients = ['pyright']

[[layers]]
    name = "lang#javascript"
    auto_fix = true
    enable_flow_syntax = false
    format_on_save = true

[[layers]]
    name = "lang#perl"

[[layers]]
    name = "lang#ruby"

[[layers]]
    name = "lang#c"
    clang_executable = "/data/data/com.termux/files/usr/bin/clang"
    enable_clang_syntax_highlight = true
    [layer.clang_std]
    c = "c17"
    cpp = "c++20"

[[layers]]
    name = "lang#r"
    repl_command = "R --no-save"

[[layers]]
    name = "git"
    git_plugin = 'vim-gitgutter'

[[layers]]
    name = "github"

[[layers]]
    name = "lang#latex"

[[layers]]
    name = "sudo"

[[layers]]
  name = "test"

[[layers]]
  name = "tools"

[[layers]]
  name = "VersionControl"

[[layers]]
  name = "ssh"

[[layers]]
  name = "lang#assembly"

[[layers]]
  name = "lang#csharp"
  highlight_types = 0

[[layers]]
  name = "lang#toml"

[[layers]]
  name = "lang#vim"

[[layers]]
  name = "lang#rust"
  recommended_style = true
  format_on_save = true

[[layers]]
  name = "lang#julia"

[[layers]]
  name = "lang#sql"

[[layers]]
  name = "lang#xml"

[[layers]]
  name = "lang#xquery"

[[layers]]
  name = "lang#groovy"

[[layers]]
  name = "lang#json"
  conceal = false
  concealcursor = ''

[[layers]]
  name = "lang#d"

[[layers]]
  name = "lang#graphql"

[[layers]]
  name = "lang#WebAssembly"

[[layers]]
  name = "lang#typescript"

[[layers]]
  name = "nvim-treesitter"

[[custom_plugins]]
    name = "MaxMEllon/vim-jsx-pretty"
    merged = false

[[custom_plugins]]
    repo = "vim-scripts/dbext.vim"
    merged = false

[[custom_plugins]]
    repo = "lilydjwg/colorizer"
    merged = false

[[custom_plugins]]
    repo = "junegunn/vim-github-dashboard"
    merged = false

[[custom_plugins]]
    repo = "github/copilot.vim"
    merged = true

[[custom_plugins]]
    repo = "nono/jquery.vim"
    merged = false

[[custom_plugins]]
    repo = 'tibabit/vim-templates'
    merged = false

[[custom_plugins]]
    repo = 'farmergreg/vim-lastplace'
    merged = true

[[custom_plugins]]
    repo = 'editorconfig/editorconfig-vim'
    merged = false

[[custom_plugins]]
    repo = 'tpope/vim-surround'
    merged = false

[[custom_plugins]]
    repo = 'scrooloose/nerdtree'
    merged = false

[[custom_plugins]]
    repo = 'scrooloose/syntastic'
    merged = false

[[custom_plugins]]
    repo = 'pangloss/vim-javascript'
    merged = false

[[custom_plugins]]
    repo = "elzr/vim-json"
    merged = true

[[custom_plugins]]
    repo = "bfrg/vim-jq"
    merged = true

[[custom_plugins]]
    repo = "XadillaX/json-formatter.vim"
    merged = true

[[custom_plugins]]
    repo = 'godlygeek/tabular'
    merged = false

[[custom_plugins]]
    repo = 'preservim/vim-markdown'
    merged = true

[[custom_plugins]]
    repo = 'mzlogin/vim-markdown-toc'
    merged = true

[[custom_plugins]]
    repo = 'z0mbix/vim-shfmt'
    merged = true

[[custom_plugins]]
    repo = 'mhinz/vim-signify'
    merged = false

[[custom_plugins]]
  repo = "mhartington/oceanic-next"
  merged = false
