#!/usr/bin/env bash

link_configurations() {
  local ret=0
  local config_dir="$HOME/Configurations"
  local home_dir="$HOME"

  if [ ! -d "$config_dir" ]; then
    echo "Error: $config_dir directory does not exist."
    return 1
  fi

  for item in "$@"; do
    local item_path="$config_dir/$item"
    local link_path="$home_dir/$item"

    if [ ! -e "$item_path" ]; then
      echo "Error: $item_path does not exist."
      continue
    fi

    if [ -e "$link_path" ]; then
      if [ -f "$link_path" ]; then
        echo "Copying ${link_path} to ${link_path}.old"
        cp -L "${link_path}" "${link_path}.old"
      fi
      if [ -d "$link_path" ]; then
        if [[ -L "$link_path" ]]; then
          local real_path
          real_path="$(readlink "$link_path")"
          if [[ "$real_path" == "$item_path" ]]; then
            echo "Skipping ${link_path} as it is linked already..."
            continue
          else
            echo "${link_path} is actually at $real_path"
            echo "Safe to link to $item_path"
            rm -rf "${link_path}"
          fi
        else
          echo "Copying ${link_path} to ${link_path}.old"
          cp -L "${link_path}" "${link_path}.old"
        fi
      fi
    fi

    echo "Creating link to $item_path"
    ln -sf "$item_path" "$link_path" || ((ret = 1))
  done

  exit "$ret"
}

function require() {
  local missing_deps=()

  for dep in "$@"; do
    if ! command -v "$dep" &> /dev/null; then
      missing_deps+=("$dep")
    fi
  done

  if [ ${#missing_deps[@]} -gt 0 ]; then
    printf "Error: The following dependencies were not found:\n" >&2
    for dep in "${missing_deps[@]}"; do
      printf "  - %s\n" "$dep" >&2
    done
    return 1
  fi
}

set -eou pipefail
shopt -s inherit_errexit

require cp

find "$HOME" -maxdepth 1 -type f -name "*.old" -name "*.old.tar" -delete -print0

link_configurations .bashrc .bash_profile .bash_aliases .bash_logout \
  .gitconfig .gitrc .github .gitguardian.yml .emacs .sqliterc .ssh .termux .tmux.conf \
  .vimrc .jupyter .aider.conf.yml .aider.model.settings.yml

# handle git differently
if [[ -L "${HOME}/.git" ]]; then
  ln -sf "${HOME}/Configurations/git" "${HOME}/.git"
else
  cp -L "${HOME}/.git" "${HOME}/.git.old"
fi
exit 0
