#!/usr/bin/env bash

link_configurations() {
  local ret=0
  local config_dir="$HOME/Configurations"
  local home_dir="$HOME"

  if [ ! -d "$config_dir" ]; then
    echo "Error: $config_dir directory does not exist."
    return 1
  fi

  for item in "$@"; do
    local item_path="$config_dir/$item"
    local link_path="$home_dir/$item"

    if [ ! -e "$item_path" ]; then
      echo "Error: $item_path does not exist."
      continue
    fi

    if [ -e "$link_path" ]; then
      echo "Removing existing $link_path"
      rm -f "$link_path"
    fi

    echo "Creating link to $item_path"
    ln -sf "$item_path" "$link_path" || ((ret = 1))
  done
  exit "$ret"
}

link_configurations .bashrc .bash_profile .bash_aliases .bash_logout \
  .gitconfig .gitrc
