#!/usr/bin/env bash
cp credentials.dot credentials
id=$(cat aws_access_key_id)
sed -i "s/{your_access_key_id}/${id}/g" credentials
key=$(cat aws_secret_access_key)
sed -i "s/{your_secret_access_key}/${key}/g" credentials
