#!/usr/bin/env bash
DEBUG=false
if [ $DEBUG ]
then
  echo "DEBUG mode on."
  set -xve
fi
exitcode=0
if [ -f /etc/os-release ]
then 
  cd ~/"$1"
  exitcode="$?"
else
  cd ~/arch/root/"$1"
  exitcode="$?"
fi
if [ $DEBUG ]
then
  set +xve
fi
exit "$exitcode"

