#!/usr/bin/env bash
DEBUG=false
$DEBUG && {
	echo "DEBUG mode on."
	set -xve
}
exitcode=0
if [ -f /etc/os-release ]; then
	cd ~/"$1"
	exitcode="$?"
else
	cd ~/arch/root/"$1"
	exitcode="$?"
fi
$DEBUG && {
	set +xve
}
exit "$exitcode"
