#!/usr/bin/env bash
#
# Script to delete broken links.
#
# The script:
# - Includes a `--dry-run` option to print links to be deleted instead of deleting them
# - Uses `rm -f` to force deletion of links without prompting for confirmation
# - Asks the user to confirm deletion for each link, with options "yes", "no", or "all"
# - If the user chooses "all", the script deletes the current link and all remaining links without asking for further confirmation

usage() {
  echo "Usage: $0 [OPTION]"
  echo "Remove broken symbolic links"
  echo ""
  echo "Options:"
  echo "  -d, --dry-run  Print links to be deleted instead of deleting"
  echo "  -h, --help  Display this help message"
  echo "  -p, --print Print list of broken links"
  exit 1
}

dry_run=false
print=false
while [ $# -gt 0 ]; do
  case $1 in
    -d | --dry-run)
      dry_run=true
      ;;
    -p | --print)
      print=true
      ;;
    -h | --help)
      usage
      ;;
    *)
      usage
      ;;
  esac
  shift
done

mapfile -t broken_links < <(find . -xtype l -print)

if [ ${#broken_links[@]} -eq 0 ]; then
  echo "No broken symbolic links found."
  exit 0
fi

if "$print"; then
  printf "%s\n" "${broken_links[@]}"
  exit 0
fi

all_links=no
# shellcheck disable=SC2162
for i in "${!broken_links[@]}"; do
  link="${broken_links[$i]}"
  read -p "Delete $link? (yes/no/all/abort): " response
  case $response in
    y | yes)
      if [[ "$dry_run" ]]; then
        echo "Would delete $link"
      else
        rm -f "$link"
        echo "Deleted $link"
      fi
      ;;
    all)
      all_links=yes
      if [[ "$dry_run" ]]; then
        echo "Would delete $link"
      else
        rm -f "$link"
        echo "Deleted $link"
      fi
      ;;
    abort)
      exit 1
      ;;
    *) ;;
  esac
  if [ "$all_links" = "yes" ]; then
    for remaining_link in "${broken_links[@]:${i}}"; do
      if [[ "$dry_run" = "yes" ]]; then
        echo "Would delete $remaining_link"
      else
        rm -f "$remaining_link"
        echo "Deleted $remaining_link"
      fi
    done
    break
  fi
done
