#!/usr/bin/env bash
if [ "$#" -ne 3 ];
then 
  echo "$0 host db script"
  echo "host - host name or ip address"
  echo "db - database name"
  echo "script - sql script"
  exit 1
fi
host="$1"
db="$2"
script="$3"
psql -U u0_a286 -h "$host" -d "$db" -f "$script" -a
exit "$?"
