#!/usr/bin/env bash
######################################################################
# @author      : Linus Fernandes (linusfernandes@gmail.com)
# @file        : gitadd
# @created     : Tuesday Feb 8, 2022 08:00:00 IST
# @copyright   : Copyright (c) Linus Fernandes
# @description :
######################################################################
function require() {
  hash "$@" || exit 127
}
# shellcheck source=/dev/null
source ~/.gitrc
require git hub
command="git add ."
eval "$command"
command="git status"
eval "$command"
exit $?
