#!/usr/bin/env bash

######################################################################
# @author      : Linus Fernandes (linusfernandes@gmail.com)
# @file        : gitadd
# @created     : Tuesday Feb 8, 2022 08:00:00 IST
# @copyright   : Copyright (c) Linus Fernandes
# @description : 
######################################################################
command="git add ."
$command
command="git status"
$command
exit $?
