#!/usr/bin/env bash

######################################################################
# @author      : Linus Fernandes (linusfernandes@gmail.com)
# @file        : gitadd
# @created     : Tuesday Feb 8, 2022 08:00:00 IST
# @copyright   : Copyright (c) Linus Fernandes
# @description :
######################################################################

function require() {
  hash "$@" || exit 127
}

set -e
# shellcheck source=/dev/null
source "${HOME}/.gitrc"

require git hub

command=("git" "add" ".")
if ! "${command[@]}"; then
  echo "Error adding files to Git staging area" >&2
  exit 1
fi

command=("git" "status")
"${command[@]}"
exit $?
