#!/usr/bin/env bash
######################################################################
# @author      : Linus Fernandes (linusfernandes@gmail.com)
# @file        : gitalias
# @created     : Friday Jan 27, 2023 04:55:00 IST
# @copyright   : Copyright (c) Linus Fernandes
# @description :
######################################################################
require() {
  hash "$@" || exit
}
require git
command="git config --get-regexp ^alias\."
eval "$command"
exit $?
