#!/usr/bin/env bash

######################################################################
# @author      : Linus Fernandes (linusfernandes@gmail.com)
# @file        : gitalias
# @created     : Friday Jan 27, 2023 04:55:00 IST
# @copyright   : Copyright (c) Linus Fernandes
# @description :
######################################################################

require() {
  hash "$@" || exit
}
set -e
require git

if ! output=$(git config --get-regexp '^alias\.'); then
  echo "Error retrieving Git aliases" >&2
  exit 1
fi

printf "%s\n" "$output"
