#!/usr/bin/env bash

require() {
  hash "$@" || exit
}

set -e
parentpath="$(dirname "$(readlink -f "$0")")"

if [[ -e "${parentpath}/internet.sh" ]]; then
  # shellcheck disable=SC1091
  source "${parentpath}/internet.sh"
fi

require gh

if [[ $# -lt 1 ]]; then
  echo "Error: repository not specified" >&2
  exit 1
fi

if ! gh repo clone "$@"; then
  echo "Error cloning repository" >&2
  exit 1
fi
