#!/usr/bin/env bash
######################################################################
# @author      : Linus Fernandes (linusfernandes@gmail.com)
# @file        : gitcommit
# @created     : Tuesday Jan 11, 2022 08:00:00 IST
# @copyright   : Copyright (c) Linus Fernandes
# @description : 
######################################################################
require() {
hash "$@" || exit
}
require git
command="git commit -F commit.txt"
eval "$command"
exit $?
