#!/usr/bin/env bash
require() {
  hash "$@" || exit
}
parentpath="$(dirname "${0}")"
if test -e "${parentpath}/internet.sh"; then
  # shellcheck disable=SC1091
  source "${parentpath}/internet.sh"
fi
require gh
gh repo clone "$@"
