#!/usr/bin/env bash
######################################################################
# @author      : Linus Fernandes (linusfernandes@gmail.com)
# @file        : gitit
# @created     : Friday Feb 11, 2022 08:00:00 IST
# @copyright   : Copyright (c) Linus Fernandes
# @description :
######################################################################
shopt -s expand_aliases
# shellcheck source=/dev/null
source "${HOME}/.gitrc"
# shellcheck source=/dev/null
source "${HOME}/.bash_aliases"
gitadd && gitcommit && gitpush
exit $?
