#!/usr/bin/env bash

######################################################################
# @author      : Linus Fernandes (linusfernandes@gmail.com)
# @file        : gitlastcommit
# @created     : Thursday Dec 15, 2022 07:43:00 IST
# @copyright   : Copyright (c) Linus Fernandes
# @description : 
######################################################################
command="git log -n 1"
$command
exit $?
