#!/usr/bin/env bash

######################################################################
# @author      : Linus Fernandes (linusfernandes@gmail.com)
# @file        : gitmerge
# @created     : Wednesday Feb 19, 2020 21:59:57 IST
# @copyright   : Copyright (c) Linus Fernandes
# @description : 
######################################################################
RED="\033[0;31m"
NC="\033[0m" # No Color

function message()
{
  ret=$?
  if [ $ret -eq 0 ]
  then
    echo exit $ret from last command: $command
  else
    echo ${RED}exit $ret from last command: $command${NC}
    echo ${RED}returning to branch development
    git checkout development
fi
  exit $ret
}

set -e
command=""
trap message EXIT

mainBranch="main"

command="git checkout ${mainBranch}"
$command
command="git config pull.rebase false"
$command
command="git pull"
$command
command="git checkout development"
$command
command="git merge ${mainBranch}"
$command
command="gitpush"
$command
