#!/usr/bin/env bash
######################################################################
# @author      : Linus Fernandes (linusfernandes@gmail.com)
# @file        : gitpush
# @created     : Thursday May 02, 2019 21:07:57 IST
# @copyright   : Copyright (c) Linus Fernandes
# @description :
######################################################################
RED="\033[0;31m"
NC="\033[0m" # No Color

function message() {
	ret=$?
	if [ "$ret" -eq 0 ]; then
		echo "exit $ret from last command: $command"
	else
		echo "${RED}exit $ret from last command: $command${NC}"
		echo "${RED}returning to branch development"
		git checkout development
	fi
	exit "$ret"
}

require() {
	hash "$@" || exit
}
require git
set -e
command=""
trap message EXIT

mainBranch="main"

command="git checkout ${mainBranch}"
eval "$command"
command="git merge development"
eval "$command"
command="git push -u origin ${mainBranch}"
eval "$command"
command="git checkout development"
eval "$command"
