#!/usr/bin/env bash
######################################################################
# @author      : Linus Fernandes (linusfernandes@gmail.com)
# @file        : gitpull
# @created     : Wednesday Feb 19, 2020 21:59:57 IST
# @copyright   : Copyright (c) Linus Fernandes
# @description :
######################################################################
RED="\033[0;31m"
NC="\033[0m" # No Color

function message() {
  ret=$?
  if [ "$ret" -eq 0 ]; then
    echo "exit $ret from last command: $command"
    git diff development main
    git gc
  else
    echo "${RED}exit $ret from last command: $command${NC}"
    echo "${RED}returning to branch development"
    git checkout development
  fi
  exit "$ret"
}

require() {
  hash "$@" || exit
}
parentpath="$(dirname "${0}")"
if test -e "${parentpath}/internet.sh"; then
  # shellcheck disable=SC1091
  source "${parentpath}/internet.sh"
fi
require git
set -e
command=""
trap message EXIT

mainBranch="main"

command="git checkout development"
eval "$command"
command="git pull"
eval "$command"
command="git checkout ${mainBranch}"
eval "$command"
command="git pull"
eval "$command"
command="git checkout development"
eval "$command"
