#!/usr/bin/env bash
######################################################################
# @author      : Linus Fernandes (linusfernandes@gmail.com)
# @file        : gitpush
# @created     : Thursday May 02, 2019 21:07:57 IST
# @copyright   : Copyright (c) Linus Fernandes
# @description :
######################################################################
RED="\033[0;31m"
NC="\033[0m" # No Color

# Don't warn about unreachable commands in this function
# shellcheck disable=SC2317
function message() {
  ret=$?
  if [ "$ret" -eq 0 ]; then
    echo "exit $ret from last command: $command"
    git diff development main
    git gc
  else
    echo "${RED}exit $ret from last command: $command${NC}"
    echo "${RED}returning to branch development"
    git checkout development
  fi
  exit "$ret"
}

require() {
  hash "$@" || exit
}
parentpath="$(dirname "${0}")"
if test -e "${parentpath}/internet.sh"; then
  # shellcheck disable=SC1091
  source "${parentpath}/internet.sh"
fi
require git
set -e
command=""
trap message EXIT

mainBranch="main"

command="git pull --rebase"
eval "$command"
command="git push -u origin development"
eval "$command"
command="git checkout ${mainBranch}"
eval "$command"
command="git merge --no-edit development"
eval "$command"
command="git pull --rebase"
eval "$command"
command="git push -u origin ${mainBranch}"
eval "$command"
command="git checkout development"
eval "$command"
command="git merge ${mainBranch}"
eval "$command"
exit $?
