#!/usr/bin/env bash
######################################################################
# @author      : Linus Fernandes (linusfernandes@gmail.com)
# @file        : gitpush
# @created     : Thursday May 02, 2019 21:07:57 IST
# @copyright   : Copyright (c) Linus Fernandes
# @description :
######################################################################
require() {
  hash "$@" || exit
}
parentpath="$(dirname "${0}")"
if test -e "${parentpath}/internet.sh"; then
  # shellcheck disable=SC1091
  source "${parentpath}/internet.sh"
fi
require git
RED="\033[0;31m"
NC="\033[0m" # No Color
set -e
command=""
trap message EXIT
function message() {
  ret=$?
  if [ "$ret" -eq 0 ]; then
    echo "exit $ret from last command: $command"
    git diff development main
    git gc
  else
    echo "${RED}exit $ret from last command: $command${NC}"
    echo "${RED}returning to branch development"
    git checkout development
  fi
  exit "$ret"
}
command="git push -u origin development"
eval "$command"
