#!/usr/bin/env bash
######################################################################
# @author      : Linus Fernandes (linusfernandes@gmail.com)
# @file        : gitrank
# @created     : Friday Jan 27, 2023 04:48:00 IST
# @copyright   : Copyright (c) Linus Fernandes
# @description :
######################################################################
require() {
  hash "$@" || exit
}
require git
command="git shortlog -s -n --no-merges"
eval "$command"
exit $?
