#!/usr/bin/env bash

######################################################################
# @author      : Linus Fernandes (linusfernandes@gmail.com)
# @file        : mkpackagedirs
# @created     : Friday May 03, 2019 08:11:52 IST
# @copyright   : Copyright (c) Linus Fernandes
# @description : Makes package directories from specified package name.
######################################################################
function require() {
hash "$@" || exit 127;
}
require mkdir
usage ()
{
  echo 'Usage : mkpackagedirs <package>'
  echo 'package - name of java package'
  exit 1
}
if test "$1" = ""; then
  usage
else
  dir="${1//\./\/}"
  echo "$dir"
  mkdir -p "$dir"
  exit $?
fi
