#!/usr/bin/env bash
function require() {
	hash "$@" || exit 127
}
require mkdir find parallel mv
mkdir -p "${PREFIX}/home/storage/downloads/${1}" /
find . -name "$2" | parallel -I% --max-args 1 mv % "${PREFIX}/home/storage/downloads/${1}"
