#!/usr/bin/env bash
function require() {
	hash "$@" || exit 127
}
require basename start-stop-daemon killall
BIND=127.0.0.1:9000
USER=u0_a286
PHP_FCGI_CHILDREN=15
PHP_FCGI_MAX_REQUESTS=1000

PHP_CGI="${PREFIX}/usr/bin/php-cgi"
PHP_CGI_NAME="$(basename "$PHP_CGI")"
PHP_CGI_ARGS="- USER=$USER PATH=${PREFIX}/usr/bin PHP_FCGI_CHILDREN=$PHP_FCGI_CHILDREN PHP_FCGI_MAX_REQUESTS=$PHP_FCGI_MAX_REQUESTS $PHP_CGI -b $BIND"
RETVAL=0

function start() {
	echo -n "Starting PHP FastCGI: "
	start-stop-daemon --quiet --start --background --chuid "$USER" --exec "${PREFIX}/usr/bin" -- "$PHP_CGI_ARGS"
	RETVAL=$?
	echo "$PHP_CGI_NAME."
}

function stop() {
	echo -n "Stopping PHP FastCGI: "
	killall -q -w -u "$USER" "$PHP_CGI"
	RETVAL=$?
	echo "$PHP_CGI_NAME."
}

case "$1" in
start)
	start
	;;
stop)
	stop
	;;
restart)
	stop
	start
	;;
*)
	echo "Usage: php-fastcgi {start|stop|restart}"
	exit 1
	;;
esac
exit "$RETVAL"
