#!/usr/bin/env bash

#######################################################################
# @author      : Linus Fernandes (linusfernandes@gmail.com)
# @file        : setupspacevim
# @created     : Wednesday Mar 12, 2025 15:08:00 IST
# @copyright   : Copyright (c) Linus Fernandes
# @description :
######################################################################

function require() {
  hash "$@" || exit 127
}

set -e

require curl vim nvim

[[ -d "${HOME}/.vim" ]] && rm -rf "${HOME}/.vim"
[[ -d "${HOME}/.config/nvim" ]] && rm -rf "${HOME}/.config/nvim"
[[ -d "${HOME}/.cache/SpaceVim" ]] && rm -rf "${HOME}/.cache/SpaceVim"
[[ -d "${HOME}/.SpaceVim" ]] && rm -rf "${HOME}/.SpaceVim"
[[ -d "${HOME}/.SpaceVim.d" ]] && rm -rf "${HOME}/.SpaceVim.d"

curl -sLf https://spacevim.org/install.sh | bash

vim

[[ -f "${HOME}/.SpaceVim.d/init.toml" ]] && mv "${HOME}/.SpaceVim.d/init.toml" "${HOME}/.SpaceVim.d/init.toml.bak" || printf "%s not found.\n" "${HOME}/.SpaceVim.d/init.toml"

[[ -f "${HOME}/Configurations/init.vim" ]] && ln -s "${HOME}/Configurations/init.vim" "${HOME}/.SpaceVim.d/init.vim" || printf "%s not found.\n" "${HOME}/.SpaceVim.d/init.vim"

exit 0
