#!/usr/bin/env bash
function require() {
	hash "$@" || exit 127
}
require mkdir mysql_install_db
(
	cd "${PREFIX}/etc" || exit 1
	mkdir my.cnf.d
)

# use the following command to install securely
# mysql_secure_installation
mysql_install_db
