#!/usr/bin/env bash
# Here's one that uploads a local script onto the live demo at shellcheck.net
shellcheck.net()
{
  if test "$#" -gt 0;
  then
    for i in "$@"
    do
      if test -f "$i"; then
        check "$i"
      else
        echo "$i is not a file."
      fi
    done
  else
    cmd="find . -maxdepth 1 -type f -executable -print"
    readarray -t execs < <(eval "$cmd")
    cmd="find . -maxdepth 1 -name '*.sh' -print"
    readarray -t scripts < <(eval "$cmd")
    scripts+=("${execs[@]}")
    for i in "${scripts[@]}"
    do
      check "$i"
    done
  fi

}

function check() {
  (curl --data-urlencode "script@$1" -sS 'https://www.shellcheck.net/shellcheck.php' | jq .) > "$1.out"
  filesize="$(stat -c%s "${1}.out")"
  if test "$filesize" -lt 4;then 
    rm -f "${1}.out"
  fi
}
shellcheck.net "$@"
