#!/usr/bin/env bash
# unpack: Extract common file formats

# Display usage if no parameters given
if [[ -z "$*" ]]; then
	echo " ${0##*/} <archive(s)> - extract common file formats)"
	exit
fi

# Required program(s)
# require functionality
req_progs=(7z unrar unzip tar bunzip2 ar gunzip uncompress)
for p in "${req_progs[@]}"; do
	hash "$p" 2>&- ||
		{
			echo >&2 " Required program \"$p\" not installed."
			exit 1
		}
done

for f in "$@"; do
	# Test if file exists
	if [ ! -f "$f" ]; then
		echo "File $f doesn't exist"
		continue
	fi
	# Extract file by using extension as reference
	case "$f" in
	*.7z) 7z x "$@" ;;
	*.tar.bz2) tar xvjf "$@" ;;
	*.bz2) bunzip2 "$@" ;;
	*.deb) ar vx "$@" ;;
	*.tar.gz) tar xvf "$@" ;;
	*.gz) gunzip "$@" ;;
	*.tar) tar xvf "$@" ;;
	*.tbz2) tar xvjf "$@" ;;
	*.tar.xz) tar xvf "$@" ;;
	*.tgz) tar xvzf "$@" ;;
	*.rar) unrar x "$@" ;;
	*.zip) unzip "$@" ;;
	*.Z) uncompress "$@" ;;
	*) echo " Unsupported file format" ;;
	esac
done
