#!/usr/bin/env bash
######################################################################
# @author      : Linus Fernandes (linusfernandes@gmail.com)
# @file        : sshagent
# @created     : Tuesday Apr 30, 2019 11:10:49 IST
# @copyright   : Copyright (c) Linus Fernandes
# @description :
######################################################################
require() {
hash "$@" || exit 127;
}
require termux-wake-lock ssh-agent
termux-wake-lock
echo "hello"
eval "$(ssh-agent -s)"
